// Mirror of code/config.py. Tune freely; nothing else hard-codes these.

export const CONFIG = {
  // Simulation
  NUM_AGENTS: 10_000,
  NUM_TICKS: 365,
  NUM_COMPANIES: 200,
  ESSENTIAL_COMPANY_RATIO: 0.30,
  RANDOM_SEED: 42,
  INITIAL_INFECTED_COUNT: 10,

  // Epidemiology
  BASE_TRANSMISSION_RATE: 0.045,
  MARKET_CONTACT_FRACTION: 0.04,
  MARKET_TRANSMISSION_SCALE: 0.55,
  INCUBATION_DAYS: 5,
  ASYMPTOMATIC_INFECTIOUS_DAYS: 4,
  SYMPTOMATIC_RECOVERY_DAYS: 10,
  ASYMPTOMATIC_RATIO: 0.40,
  BASE_DAILY_MORTALITY_RATE: 0.007,
  HEALTHCARE_OVERFLOW_MORTALITY_MULTIPLIER: 2.0,
  MASK_TRANSMISSION_REDUCTION: 0.50,
  LOCKDOWN_TRANSMISSION_MULTIPLIER: [1.0, 0.7, 0.4, 0.15],
  VACCINATIONS_PER_DAY_PER_RATE: 0.003,

  // Economy
  INITIAL_WALLET_MEAN: 1_200,
  INITIAL_WALLET_STD: 400,
  INITIAL_WALLET_MIN: 150,
  BASE_CONSUMPTION_MEAN: 55,
  BASE_CONSUMPTION_STD: 18,
  BASE_CONSUMPTION_MIN: 15,
  DAILY_WAGE: 80,
  PRODUCTIVITY_CONSTANT: 120,
  INITIAL_COMPANY_CASH_MEAN: 80_000,
  INITIAL_COMPANY_CASH_STD: 25_000,
  INITIAL_COMPANY_CASH_MIN: 10_000,
  ESSENTIAL_DEMAND_BASE: 0.90,
  NON_ESSENTIAL_DEMAND_BASE: 0.75,
  LOCKDOWN_NON_ESSENTIAL_PENALTY: 0.22,
  DEATH_DEMAND_SUPPRESSION_FACTOR: 0.00004,

  // Poverty Trap
  POVERTY_TRAP_MULTIPLIER: 3,

  // Labour
  WORKFORCE_STRUGGLING_THRESHOLD: 0.50,
  FIRING_PROBABILITY: 0.10,
  BANKRUPTCY_CASH_THRESHOLD: -120_000,
  BASE_REHIRE_PROBABILITY: 0.005,
  REHIRE_HEALTHY_COMPANY_CASH_MIN: 5_000,
  REHIRE_HEALTHY_WORKFORCE_RATIO: 0.7,
  SYMPTOMATIC_WORK_ATTENDANCE_FACTOR: 0.30,
  SYMPTOMATIC_MARKET_ATTENDANCE_FACTOR: 0.10,

  // Banking
  BANK_INITIAL_RESERVES: 15_000_000,
  BANK_RESERVE_THRESHOLD: 2_500_000,
  BANK_LOAN_AMOUNT: 50_000,
  BANK_MAX_LOAN_MULTIPLE: 3,
  BANK_NORMAL_INTEREST_RATE: 0.0001,
  BANK_CRISIS_INTEREST_RATE: 0.0005,
  BANK_LOAN_REPAYMENT_RATE: 0.008,

  // Healthcare
  HEALTHCARE_BED_CAPACITY: 500,

  // Government Defaults
  INITIAL_LOCKDOWN_LEVEL: 0,
  INITIAL_MASK_MANDATE: false,
  INITIAL_STIMULUS_AMOUNT: 0,
  INITIAL_VACCINATION_RATE: 0,
  STIMULUS_WALLET_THRESHOLD: 300,
} as const

export type LockdownLevel = 0 | 1 | 2 | 3
